### ISSUE TITLE
Too many "/tmp/.org.chromium.Chromium.xxxxxx", maybe relate to element

### ISSUE THREAD

**Issue by please-enter-a-username** [tuxedocomputers/tuxedo-control-center#351]
Title says all. TCC creates too many trash and doesn't cleanup.
```
Under /root/.config/tuxedo-control-center/
...
lrwxrwxrwx 1 root root   37 Dec 30 21:35 SS -> /tmp/.org.chromium.Chromium.2kABxu/SS
...
```
```
Under /home/user/.config/tuxedo-control-center/
...
-rw-------  1 user users  624 Dec 30 22:04 .org.chromium.Chromium.PKcZSw
-rw-------  1 user users  624 Jan  6 02:28 .org.chromium.Chromium.WpVYVu
lrwxrwxrwx  1 user users   37 Jan 16 15:32 SS -> /tmp/.org.chromium.Chromium.v2ZZa0/SS
...
```
```
Under /tmp/
...
drwx------   2 user users   4096 Dec 31 18:26 .org.chromium.Chromium.0M12dx
drwx------   2 user users   4096 Dec 31 17:10 .org.chromium.Chromium.0RkQyS
drwx------   2 root root    4096 Dec 30 21:35 .org.chromium.Chromium.2kABxu
drwx------   2 user users   4096 Jan  4 04:33 .org.chromium.Chromium.2uf9Db
drwx------   2 user users   4096 Dec 31 18:11 .org.chromium.Chromium.2yfB8N
drwx------   3 user users   4096 Jan  4 00:51 .org.chromium.Chromium.3HwHUr
drwx------   2 user users   4096 Jan  1 12:06 .org.chromium.Chromium.3LsY28
drwx------   3 user users   4096 Jan  4 18:14 .org.chromium.Chromium.3czApl
drwx------   2 user users   4096 Jan  4 02:35 .org.chromium.Chromium.3elBuu
-rwxr-xr-x   1 user users  89216 Dec 30 20:50 .org.chromium.Chromium.4I9ksn
drwx------   2 user users   4096 Jan  8 08:20 .org.chromium.Chromium.4itGWj
drwx------   2 user users   4096 Jan  3 19:37 .org.chromium.Chromium.4uH7Fb
drwx------   3 user users   4096 Dec 31 18:11 .org.chromium.Chromium.4vSH4O
drwx------   2 user users   4096 Jan  5 13:01 .org.chromium.Chromium.5ZLDMx
drwx------   3 user users   4096 Jan  4 11:47 .org.chromium.Chromium.5lJOaZ
drwx------   3 user users   4096 Jan 16 08:26 .org.chromium.Chromium.6Bm8kB
drwx------   2 user users   4096 Dec 31 18:34 .org.chromium.Chromium.78kfl5
drwx------   3 user users   4096 Jan  2 14:10 .org.chromium.Chromium.8Fdkr3
drwx------   3 user users   4096 Dec 31 18:34 .org.chromium.Chromium.8rkxz4
drwx------   2 user users   4096 Jan  4 01:34 .org.chromium.Chromium.9Tburc
drwx------   2 user users   4096 Jan  2 14:10 .org.chromium.Chromium.9jgL55
drwx------   2 user users   4096 Jan 12 08:22 .org.chromium.Chromium.9tYwDj
drwx------   3 user users   4096 Jan  4 01:39 .org.chromium.Chromium.9y5iQF
drwx------   2 user users   4096 Jan  9 08:20 .org.chromium.Chromium.AYAbOm
drwx------   2 user users   4096 Jan  4 12:27 .org.chromium.Chromium.BN1eCt
drwx------   3 user users   4096 Dec 31 17:08 .org.chromium.Chromium.BQ7QgJ
drwx------   2 user users   4096 Dec 31 11:55 .org.chromium.Chromium.BR4r2W
drwx------   2 user users   4096 Dec 31 21:36 .org.chromium.Chromium.BVu5eI
drwx------   3 user users   4096 Jan  3 19:42 .org.chromium.Chromium.BzLf3O
drwx------   2 user users   4096 Jan  1 11:57 .org.chromium.Chromium.CEjtlB
drwx------   3 user users   4096 Jan 14 20:57 .org.chromium.Chromium.CRaTdA
drwx------   3 user users   4096 Dec 30 22:49 .org.chromium.Chromium.Cm4KfF
drwx------   2 user users   4096 Dec 30 20:44 .org.chromium.Chromium.CyVHuV
drwx------   3 user users   4096 Jan  2 18:56 .org.chromium.Chromium.EfUM7N
drwx------   2 user users   4096 Jan 14 20:57 .org.chromium.Chromium.FVQjkA
drwx------   2 user users   4096 Jan  4 01:39 .org.chromium.Chromium.GaNgYH
drwx------   2 user users   4096 Dec 31 10:32 .org.chromium.Chromium.HgtQJV
drwx------   2 user users   4096 Jan  4 05:49 .org.chromium.Chromium.I7GtLT
drwx------   3 user users   4096 Dec 31 10:32 .org.chromium.Chromium.IAxzMU
drwx------   2 user users   4096 Jan  3 19:42 .org.chromium.Chromium.IJRkkQ
drwx------   2 user users   4096 Dec 31 17:08 .org.chromium.Chromium.IPRopK
drwx------   2 user users   4096 Jan  4 00:51 .org.chromium.Chromium.IdacAt
drwx------   2 user users   4096 Jan  4 03:43 .org.chromium.Chromium.J9OsFX
drwx------   3 user users   4096 Jan  4 12:27 .org.chromium.Chromium.JOLVdv
drwx------   2 user users   4096 Jan  6 02:22 .org.chromium.Chromium.JdwHzP
drwx------   3 user users   4096 Jan  1 12:04 .org.chromium.Chromium.JyvOsw
drwx------   2 user users   4096 Jan  6 02:30 .org.chromium.Chromium.KRwiQj
drwx------   3 user users   4096 Jan  9 11:10 .org.chromium.Chromium.Ko57as
drwx------   2 user users   4096 Dec 31 19:49 .org.chromium.Chromium.Kw1zDV
drwx------   3 user users   4096 Jan  4 03:28 .org.chromium.Chromium.LFFxkG
drwx------   3 user users   4096 Jan  1 11:48 .org.chromium.Chromium.LSBJvl
drwx------   2 user users   4096 Jan  5 16:16 .org.chromium.Chromium.Mj9BB6
drwx------   3 user users   4096 Jan  7 22:44 .org.chromium.Chromium.MtLaHx
-rwxr-xr-x   1 user users  89216 Dec 31 18:14 .org.chromium.Chromium.NDOgHP
drwx------   3 user users   4096 Dec 31 18:01 .org.chromium.Chromium.NXHC23
drwx------   3 user users   4096 Jan 12 08:22 .org.chromium.Chromium.NmFrLg
drwx------   2 user users   4096 Jan 15 08:38 .org.chromium.Chromium.O2oP0S
drwx------   2 user users   4096 Dec 31 19:33 .org.chromium.Chromium.OBsoZ5
drwx------   2 user users   4096 Jan  3 20:26 .org.chromium.Chromium.P9Sr7U
drwx------   3 user users   4096 Jan  3 17:30 .org.chromium.Chromium.PHtudV
drwx------   3 user users   4096 Dec 30 20:44 .org.chromium.Chromium.PaauBS
drwx------   3 user users   4096 Jan  8 08:20 .org.chromium.Chromium.PilRli
drwx------   2 user users   4096 Dec 31 23:04 .org.chromium.Chromium.R9jaTT
drwx------   3 user users   4096 Jan  6 02:22 .org.chromium.Chromium.S2ovxR
drwx------   2 user users   4096 Dec 31 18:01 .org.chromium.Chromium.S7RAo0
-rwxr-xr-x   1 user users  89216 Jan  4 04:25 .org.chromium.Chromium.SPk7im
drwx------   3 user users   4096 Dec 31 23:35 .org.chromium.Chromium.SZmZI5
drwx------   3 user users   4096 Dec 31 21:36 .org.chromium.Chromium.SnjI0H
drwx------   2 user users   4096 Jan  7 23:31 .org.chromium.Chromium.SnqMjA
drwx------   2 user users   4096 Jan 16 08:26 .org.chromium.Chromium.T7PZgB
drwx------   3 user users   4096 Jan  5 16:16 .org.chromium.Chromium.TZMxD8
drwx------   2 user users   4096 Jan  3 17:30 .org.chromium.Chromium.UUzrgX
drwx------   3 user users   4096 Dec 31 17:10 .org.chromium.Chromium.UXdxAU
drwx------   3 user users   4096 Jan  4 04:59 .org.chromium.Chromium.WeKfAC
drwx------   2 user users   4096 Jan  3 20:00 .org.chromium.Chromium.XAChIz
drwx------   3 user users   4096 Jan  1 11:53 .org.chromium.Chromium.XjvviC
drwx------   3 user users   4096 Jan  3 20:00 .org.chromium.Chromium.XvEeGA
drwx------   2 user users   4096 Dec 31 18:30 .org.chromium.Chromium.YykL2P
drwx------   2 user users   4096 Dec 31 23:35 .org.chromium.Chromium.ZGETU4
drwx------   3 user users   4096 Jan  1 12:06 .org.chromium.Chromium.ZJFNt8
drwx------   2 user users   4096 Jan  4 13:57 .org.chromium.Chromium.ZelIYT
drwx------   3 user users   4096 Dec 31 22:03 .org.chromium.Chromium.ZpJ9fY
drwx------   2 user users   4096 Jan  4 04:49 .org.chromium.Chromium.a03RUL
drwx------   2 user users   4096 Jan  4 04:59 .org.chromium.Chromium.a2AoID
drwx------   3 user users   4096 Jan  4 04:33 .org.chromium.Chromium.aADqy9
drwx------   2 user users   4096 Dec 30 20:49 .org.chromium.Chromium.aG0Wpm
drwx------   3 user users   4096 Dec 31 23:04 .org.chromium.Chromium.aHUc4T
drwx------   2 user users   4096 Jan  4 04:29 .org.chromium.Chromium.aqkao3
drwx------   3 user users   4096 Dec 31 11:55 .org.chromium.Chromium.axn0YY
drwx------   3 user users   4096 Jan  5 18:21 .org.chromium.Chromium.bXVRZe
drwx------   2 user users   4096 Jan  4 11:47 .org.chromium.Chromium.c6r0ZX
drwx------   2 user users   4096 Jan  1 11:48 .org.chromium.Chromium.cE4ZBk
drwx------   2 user users   4096 Jan  1 11:53 .org.chromium.Chromium.cEqCnF
drwx------   3 user users   4096 Jan  2 21:05 .org.chromium.Chromium.cOZdWG
drwx------   2 user users   4096 Jan  4 03:28 .org.chromium.Chromium.cQiujJ
drwx------   2 user users   4096 Jan  4 19:59 .org.chromium.Chromium.d3dV5i
drwx------   3 user users   4096 Jan  5 13:01 .org.chromium.Chromium.dVsLtz
drwx------   2 user users   4096 Dec 30 22:49 .org.chromium.Chromium.dcRJ8F
drwx------   3 user users   4096 Jan  4 19:59 .org.chromium.Chromium.ddOUNj
drwx------   3 user users   4096 Jan  6 02:30 .org.chromium.Chromium.eKINcl
drwx------   3 user users   4096 Jan  9 08:20 .org.chromium.Chromium.eODYcl
drwx------   3 user users   4096 Jan  4 02:35 .org.chromium.Chromium.ePFXcr
drwx------   3 user users   4096 Jan 11 08:19 .org.chromium.Chromium.eVvnD2
drwx------   3 user users   4096 Dec 31 18:26 .org.chromium.Chromium.f28hmv
drwx------   2 user users   4096 Jan  7 22:44 .org.chromium.Chromium.fnkcDx
drwx------   3 user users   4096 Jan  3 20:26 .org.chromium.Chromium.hK80JV
drwx------   2 user users   4096 Jan  5 18:21 .org.chromium.Chromium.hZeKtg
drwx------   2 user users   4096 Jan  4 18:14 .org.chromium.Chromium.i0Wlyi
drwx------   2 user users   4096 Jan 16 15:19 .org.chromium.Chromium.i695bs
drwx------   3 user users   4096 Jan  4 05:49 .org.chromium.Chromium.iA9DTU
drwx------   2 user users   4096 Dec 31 20:20 .org.chromium.Chromium.iFGOI5
drwx------   3 user users   4096 Jan 15 08:38 .org.chromium.Chromium.jGwXhT
drwx------   3 user users   4096 Dec 30 20:49 .org.chromium.Chromium.jVTp7m
drwx------   2 user users   4096 Dec 31 23:54 .org.chromium.Chromium.k9tAsR
drwx------   3 user users   4096 Jan  4 04:29 .org.chromium.Chromium.kXSlS3
drwx------   3 user users   4096 Jan  4 13:57 .org.chromium.Chromium.kXsGRW
drwx------   2 user users   4096 Dec 30 21:54 .org.chromium.Chromium.kecqhY
drwx------   3 user users   4096 Dec 31 22:13 .org.chromium.Chromium.l3ku8H
drwx------   3 user users   4096 Dec 31 23:54 .org.chromium.Chromium.lQTZ2R
drwx------   2 user users   4096 Dec 31 11:11 .org.chromium.Chromium.lWA6cN
drwx------   3 user users   4096 Jan  4 04:49 .org.chromium.Chromium.ljORlK
drwx------   3 user users   4096 Dec 31 18:04 .org.chromium.Chromium.mxcYfP
drwx------   3 user users   4096 Jan  4 03:43 .org.chromium.Chromium.n8wWpW
drwx------   3 user users   4096 Jan 16 15:32 .org.chromium.Chromium.ocQ4yY
drwx------   2 user users   4096 Jan  4 18:09 .org.chromium.Chromium.oe8SH0
drwx------   3 user users   4096 Dec 31 18:30 .org.chromium.Chromium.ovCYbQ
drwx------   2 user users   4096 Dec 31 18:04 .org.chromium.Chromium.p4XbLN
drwx------   3 user users   4096 Dec 31 19:33 .org.chromium.Chromium.pLR9l6
drwx------   2 user users   4096 Jan  9 11:10 .org.chromium.Chromium.pzOqDs
drwx------   3 user users   4096 Jan 16 15:19 .org.chromium.Chromium.r9PItq
drwx------   3 user users   4096 Dec 31 21:48 .org.chromium.Chromium.rP9k73
drwx------   2 user users   4096 Jan 11 08:19 .org.chromium.Chromium.rQsIO2
drwx------   3 user users   4096 Jan  2 00:01 .org.chromium.Chromium.sFKfu2
drwx------   2 user users   4096 Jan  1 12:04 .org.chromium.Chromium.sszeow
drwx------   2 user users   4096 Dec 31 22:13 .org.chromium.Chromium.svL7SJ
drwx------   3 user users   4096 Jan  1 11:57 .org.chromium.Chromium.t1XhzC
drwx------   2 user users   4096 Jan  2 00:01 .org.chromium.Chromium.t38Et0
drwx------   3 user users   4096 Dec 31 11:11 .org.chromium.Chromium.tIsAoM
drwx------   3 user users   4096 Jan  7 23:31 .org.chromium.Chromium.tkLW4w
drwx------   2 user users   4096 Dec 31 22:03 .org.chromium.Chromium.ttk77V
drwx------   2 user users   4096 Jan 16 15:32 .org.chromium.Chromium.v2ZZa0
drwx------   2 user users   4096 Jan  2 18:56 .org.chromium.Chromium.w4o9TN
drwx------   3 user users   4096 Jan  4 18:09 .org.chromium.Chromium.w6NwFY
drwx------   2 user users   4096 Jan  2 21:05 .org.chromium.Chromium.wdetTH
drwx------   3 user users   4096 Dec 30 21:54 .org.chromium.Chromium.wvjHTV
drwx------   3 user users   4096 Dec 31 19:49 .org.chromium.Chromium.xQbcQR
drwx------   3 user users   4096 Jan  4 01:34 .org.chromium.Chromium.xysLLc
drwx------   2 user users   4096 Dec 31 21:48 .org.chromium.Chromium.y3yYIZ
drwx------   3 user users   4096 Dec 31 20:20 .org.chromium.Chromium.yp2br4
drwx------   3 user users   4096 Jan  3 19:37 .org.chromium.Chromium.yptjab
...
```

What the h*ll?

**Comment by please-enter-a-username** [comment]
OS: openSUSE Leap 15.5
tuxedo-control-center: 2.1.2-1 (current newest version)
tuxedo-drivers: 4.0.2-1 (can not update to 4.0.3-1 due to not compatible with dkms 2.8.8)

**Comment by tuxedoherbert** [comment]
Solved with latest release

**Comment by tuxedoder** [comment]
I don't really think that this is fixed. I tried to reproduce this on several devices, but I can't go above around 4 files. Rebooting and standby does not create more files. I also tried multiple operating systems. I would appropriate if someone knows how to trigger this.

**Comment by please-enter-a-username** [comment]
Yeah I upgraded to newest version TCC today and the problem still exists.
I think it creates new folders on boot and reboot, not suspend to disk, not suspend to memory.
If more info is needed, I'm glad to help.
![image](https://github.com/tuxedocomputers/tuxedo-control-center/assets/132082853/c436ceab-a57f-4f08-a655-d373d7d8fa7e)
![image](https://github.com/tuxedocomputers/tuxedo-control-center/assets/132082853/279af610-94d2-4889-94f1-8a459882c10d)

**Comment by please-enter-a-username** [comment]
Sorry misoperation, the issue should remain opened.
